Delete http://localhost:3003/api/blogs/6911d114c8d78872a11906ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVkZW1RIiwiaWQiOiI2OTA4ZWFlZjFmNjJjZWQ0YTkyZjYyNjIiLCJpYXQiOjE3NjI3ODE3MjF9.FCOJ2EmhCa5FXP3vtDbHna7bo29waAAcYIdtePSHMg8